### ISSUE TITLE
Congrats!

### ISSUE THREAD

**Issue by fossfreedom** [prateekmedia/budgie-systemmonitor-applet#1]
Well done for forking and enhancing this applet.  I'm sure everyone would agree :)

FYI - I have packaged v0.2.1 for Ubuntu Budgie - its available via our backports PPA for 20.04/20.10

    sudo add-apt-repository ppa:ubuntubudgie/backports
    sudo apt install budgie-sys-monitor-applet

**Comment by prateekmedia** [comment]
Thanks, 
I wanted the features from your applet like netspeed + With icons + Natively using vala for Budgie; that's why I forked it.

**Comment by prateekmedia** [comment]
> Well done for forking and en...

@fossfreedom Also Gtk4 has released will it affect the gtk+-3 applets cause Upstream budgie 11 will be with Gtk-4 and Gnome 40 will also have it.

Or will they be compatible?

**Comment by fossfreedom** [comment]
That's TBD really.

GNOME 40 will not impact budgie - the key component is the window manager
mutter which isn't reliant on GTK+3 or 4

I suspect all applets will need to be recompiled with GTK+4 once budgie-11
is available.

**Comment by prateekmedia** [comment]
Ok TFI Closing this for Now
